name: Build Kivy App with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip libffi-dev libssl-dev
          sudo apt-get install -y python3-setuptools
          sudo apt-get install -y libncurses5-dev libstdc++6 zlib1g-dev libsqlite3-dev
          sudo apt-get install -y python3-distutils
          pip install buildozer

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get install -y libncurses5-dev libstdc++6 zlib1g-dev
          sudo apt-get install -y libsqlite3-dev

      - name: Run Buildozer to build APK
        run: |
          buildozer android debug
