name: Build Kivy App with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip libffi-dev libssl-dev
          sudo apt-get install -y python3-setuptools
          sudo apt-get install -y libncurses5-dev libstdc++6 zlib1g-dev libsqlite3-dev
          pip install cython
          pip install buildozer

      - name: Install Android SDK command line tools
        run: |
          sudo apt-get install -y wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          mkdir -p /home/runner/android-sdk/cmdline-tools
          unzip commandlinetools-linux-6609375_latest.zip -d /home/runner/android-sdk/cmdline-tools
          rm commandlinetools-linux-6609375_latest.zip
          mv /home/runner/android-sdk/cmdline-tools/cmdline-tools/* /home/runner/android-sdk/cmdline-tools/
          rmdir /home/runner/android-sdk/cmdline-tools/cmdline-tools
          echo "y" | /home/runner/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          /home/runner/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-30"

      - name: Set environment variables for Android SDK
        run: |
          echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get install -y libncurses5-dev libstdc++6 zlib1g-dev
          sudo apt-get install -y libsqlite3-dev

      - name: Run Buildozer to build APK
        run: |
          buildozer android debug
